"""use timezone-aware timestamps and Decimal for cost

Revision ID: 35617fbafeb4
Revises: 5a165fbf2690
Create Date: 2026-01-20 14:20:35.063762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35617fbafeb4'
down_revision: Union[str, None] = '5a165fbf2690'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When action occurred',
               existing_nullable=False)
    op.alter_column('conversations', 'session_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When conversation session started',
               existing_nullable=False)
    op.alter_column('conversations', 'session_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When conversation session ended',
               existing_nullable=True)
    op.alter_column('conversations', 'last_summarized',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When last reduction/summarization occurred',
               existing_nullable=True)
    op.alter_column('item_links', 'created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When link was created',
               existing_nullable=False)
    op.alter_column('items', 'created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('items', 'modified',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Last modification timestamp',
               existing_nullable=False)
    op.alter_column('items', 'last_worked',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Last time item was actively worked on',
               existing_nullable=True)
    op.alter_column('items', 'categorized_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When item was last categorized',
               existing_nullable=True)
    op.alter_column('items', 'next_surface',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When to surface this item next',
               existing_nullable=True)
    op.alter_column('items', 'embedding_updated',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When embedding was last generated',
               existing_nullable=True)
    op.alter_column('prompts', 'created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Prompt creation timestamp',
               existing_nullable=False)
    op.alter_column('token_usage', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='When the operation occurred',
               existing_nullable=False)
    op.alter_column('users', 'created',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='Account creation timestamp',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Account creation timestamp',
               existing_nullable=False)
    op.alter_column('token_usage', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When the operation occurred',
               existing_nullable=False)
    op.alter_column('prompts', 'created',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Prompt creation timestamp',
               existing_nullable=False)
    op.alter_column('items', 'embedding_updated',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When embedding was last generated',
               existing_nullable=True)
    op.alter_column('items', 'next_surface',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When to surface this item next',
               existing_nullable=True)
    op.alter_column('items', 'categorized_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When item was last categorized',
               existing_nullable=True)
    op.alter_column('items', 'last_worked',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Last time item was actively worked on',
               existing_nullable=True)
    op.alter_column('items', 'modified',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Last modification timestamp',
               existing_nullable=False)
    op.alter_column('items', 'created',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('item_links', 'created',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When link was created',
               existing_nullable=False)
    op.alter_column('conversations', 'last_summarized',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When last reduction/summarization occurred',
               existing_nullable=True)
    op.alter_column('conversations', 'session_end',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When conversation session ended',
               existing_nullable=True)
    op.alter_column('conversations', 'session_start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When conversation session started',
               existing_nullable=False)
    op.alter_column('audit_log', 'timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='When action occurred',
               existing_nullable=False)
    # ### end Alembic commands ###
