"""Initial schema with 9 tables

Revision ID: 5a165fbf2690
Revises: 
Create Date: 2026-01-17 23:38:56.117025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5a165fbf2690"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompts",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique prompt identifier"),
        sa.Column(
            "name",
            sa.String(),
            nullable=False,
            comment="Prompt name (e.g., 'classify_item')",
        ),
        sa.Column(
            "version",
            sa.String(),
            nullable=False,
            comment="Prompt version (e.g., 'v1.0', 'v2.0')",
        ),
        sa.Column(
            "content", sa.String(), nullable=False, comment="Prompt template content"
        ),
        sa.Column(
            "model_config",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="AI model configuration (temperature, max_tokens, etc.)",
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            nullable=False,
            comment="Whether this prompt version is active",
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            nullable=False,
            comment="Prompt creation timestamp",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uq_prompt_name_version"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique user identifier"),
        sa.Column(
            "email", sa.String(), nullable=False, comment="User email address (unique)"
        ),
        sa.Column(
            "created",
            sa.DateTime(),
            nullable=False,
            comment="Account creation timestamp",
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="User preferences and settings (JSONB)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "items",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique item identifier"),
        sa.Column("title", sa.String(length=500), nullable=False, comment="Item title"),
        sa.Column(
            "file_path", sa.String(), nullable=False, comment="Vault file path (unique)"
        ),
        sa.Column(
            "category",
            sa.String(length=50),
            nullable=True,
            comment="Primary category (ideas, tasks, notes, resources, journal)",
        ),
        sa.Column(
            "subcategory",
            sa.String(length=100),
            nullable=True,
            comment="Secondary classification",
        ),
        sa.Column(
            "tags",
            sa.ARRAY(sa.String()),
            nullable=True,
            comment="Tags for categorization (GIN indexed)",
        ),
        sa.Column(
            "state",
            sa.Enum(
                "UNCATEGORIZED",
                "NOT_STARTED",
                "IN_PROGRESS",
                "COMPLETED",
                "ARCHIVED",
                name="item_state",
            ),
            nullable=False,
            comment="Current workflow state",
        ),
        sa.Column(
            "created", sa.DateTime(), nullable=False, comment="Creation timestamp"
        ),
        sa.Column(
            "modified",
            sa.DateTime(),
            nullable=False,
            comment="Last modification timestamp",
        ),
        sa.Column(
            "last_worked",
            sa.DateTime(),
            nullable=True,
            comment="Last time item was actively worked on",
        ),
        sa.Column(
            "categorized_at",
            sa.DateTime(),
            nullable=True,
            comment="When item was last categorized",
        ),
        sa.Column(
            "next_surface",
            sa.DateTime(),
            nullable=True,
            comment="When to surface this item next",
        ),
        sa.Column(
            "cadence",
            sa.String(length=20),
            nullable=True,
            comment="Surfacing cadence (daily, weekly, monthly)",
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=True,
            comment="AI classification confidence (0.0-1.0)",
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
            comment="Vector embedding for similarity search (1536 dimensions)",
        ),
        sa.Column(
            "embedding_updated",
            sa.DateTime(),
            nullable=True,
            comment="When embedding was last generated",
        ),
        sa.Column(
            "content_hash",
            sa.String(length=64),
            nullable=True,
            comment="Content hash for change detection",
        ),
        sa.Column(
            "no_ai", sa.Boolean(), nullable=False, comment="Opt-out of AI processing"
        ),
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="Owner user (multi-tenant)"
        ),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            nullable=True,
            comment="Full-text search vector (auto-populated by trigger)",
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_item_confidence_range"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_path"),
    )
    op.create_index(
        "idx_items_search_vector",
        "items",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_items_tags", "items", ["tags"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_items_category"), "items", ["category"], unique=False)
    op.create_index(
        op.f("ix_items_next_surface"), "items", ["next_surface"], unique=False
    )
    op.create_index(op.f("ix_items_state"), "items", ["state"], unique=False)
    op.create_index(op.f("ix_items_user_id"), "items", ["user_id"], unique=False)
    op.create_table(
        "token_usage",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique usage record identifier"
        ),
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="User who incurred the usage"
        ),
        sa.Column(
            "operation",
            sa.String(),
            nullable=False,
            comment="Operation type (classification, embedding, chat, etc.)",
        ),
        sa.Column(
            "model",
            sa.String(),
            nullable=False,
            comment="AI model used (gpt-4, text-embedding-ada-002, etc.)",
        ),
        sa.Column(
            "input_tokens",
            sa.Integer(),
            nullable=False,
            comment="Number of input tokens consumed",
        ),
        sa.Column(
            "output_tokens",
            sa.Integer(),
            nullable=False,
            comment="Number of output tokens generated",
        ),
        sa.Column(
            "cost_usd",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="Cost in USD (precise to 6 decimals)",
        ),
        sa.Column(
            "timestamp",
            sa.DateTime(),
            nullable=False,
            comment="When the operation occurred",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_usage_timestamp"), "token_usage", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_token_usage_user_id"), "token_usage", ["user_id"], unique=False
    )
    op.create_table(
        "user_config",
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="Reference to user (composite PK part 1)",
        ),
        sa.Column(
            "key",
            sa.String(),
            nullable=False,
            comment="Configuration key (composite PK part 2)",
        ),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Configuration value (JSONB)",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "key"),
    )
    op.create_table(
        "audit_log",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique audit log entry identifier"
        ),
        sa.Column(
            "user_id",
            sa.UUID(),
            nullable=False,
            comment="User who performed the action",
        ),
        sa.Column(
            "item_id",
            sa.UUID(),
            nullable=True,
            comment="Item affected (nullable, SET NULL on delete to preserve audit)",
        ),
        sa.Column(
            "action",
            sa.String(),
            nullable=False,
            comment="Action performed (create, update, delete, classify, etc.)",
        ),
        sa.Column(
            "before",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="State before change",
        ),
        sa.Column(
            "after",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="State after change",
        ),
        sa.Column(
            "timestamp", sa.DateTime(), nullable=False, comment="When action occurred"
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_log_item_id"), "audit_log", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_timestamp"), "audit_log", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False
    )
    op.create_table(
        "conversations",
        sa.Column(
            "id", sa.UUID(), nullable=False, comment="Unique conversation identifier"
        ),
        sa.Column(
            "item_id",
            sa.UUID(),
            nullable=False,
            comment="Item this conversation is about",
        ),
        sa.Column(
            "user_id", sa.UUID(), nullable=False, comment="User in the conversation"
        ),
        sa.Column(
            "session_start",
            sa.DateTime(),
            nullable=False,
            comment="When conversation session started",
        ),
        sa.Column(
            "session_end",
            sa.DateTime(),
            nullable=True,
            comment="When conversation session ended",
        ),
        sa.Column(
            "full_transcript",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Complete conversation transcript (Retain phase)",
        ),
        sa.Column(
            "detailed_summary",
            sa.String(),
            nullable=True,
            comment="Detailed summary of conversation (Reduce phase)",
        ),
        sa.Column(
            "brief_summary",
            sa.String(),
            nullable=True,
            comment="Brief summary for long-term retention (Reduce phase)",
        ),
        sa.Column(
            "key_outcomes",
            sa.String(),
            nullable=True,
            comment="Permanent distilled insights (Retain permanently)",
        ),
        sa.Column(
            "detail_level",
            sa.String(),
            nullable=True,
            comment="Current retention level (full, detailed, brief)",
        ),
        sa.Column(
            "last_summarized",
            sa.DateTime(),
            nullable=True,
            comment="When last reduction/summarization occurred",
        ),
        sa.Column(
            "changes_made",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="What edits resulted from this conversation",
        ),
        sa.ForeignKeyConstraint(["item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversations_item_id"), "conversations", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_conversations_session_start"),
        "conversations",
        ["session_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    op.create_table(
        "item_links",
        sa.Column("id", sa.UUID(), nullable=False, comment="Unique link identifier"),
        sa.Column(
            "from_item_id",
            sa.UUID(),
            nullable=False,
            comment="Source item in relationship",
        ),
        sa.Column(
            "to_item_id",
            sa.UUID(),
            nullable=False,
            comment="Target item in relationship",
        ),
        sa.Column(
            "link_type",
            sa.String(),
            nullable=False,
            comment="Relationship type (related, references, depends-on, etc.)",
        ),
        sa.Column(
            "why_related",
            sa.String(),
            nullable=True,
            comment="Explanation of the relationship",
        ),
        sa.Column(
            "confidence",
            sa.Float(),
            nullable=True,
            comment="AI confidence in this relationship (0.0-1.0)",
        ),
        sa.Column(
            "created", sa.DateTime(), nullable=False, comment="When link was created"
        ),
        sa.CheckConstraint(
            "from_item_id != to_item_id", name="ck_item_link_no_self_links"
        ),
        sa.ForeignKeyConstraint(["from_item_id"], ["items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_item_id"], ["items.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_item_id", "to_item_id", "link_type", name="uq_item_link_from_to_type"
        ),
    )
    op.create_index(
        op.f("ix_item_links_from_item_id"), "item_links", ["from_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_item_links_to_item_id"), "item_links", ["to_item_id"], unique=False
    )

    # Create PostgreSQL trigger for auto-populating search_vector
    op.execute(
        """
        CREATE OR REPLACE FUNCTION items_search_vector_update() RETURNS trigger AS $$
        BEGIN
            NEW.search_vector := to_tsvector('english',
                COALESCE(NEW.title, '') || ' ' ||
                COALESCE(NEW.category, '') || ' ' ||
                COALESCE(NEW.subcategory, '') || ' ' ||
                array_to_string(COALESCE(NEW.tags, ARRAY[]::text[]), ' ')
            );
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER items_search_vector_trigger
            BEFORE INSERT OR UPDATE ON items
            FOR EACH ROW EXECUTE FUNCTION items_search_vector_update();
    """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop search_vector trigger and function
    op.execute("DROP TRIGGER IF EXISTS items_search_vector_trigger ON items;")
    op.execute("DROP FUNCTION IF EXISTS items_search_vector_update();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_item_links_to_item_id"), table_name="item_links")
    op.drop_index(op.f("ix_item_links_from_item_id"), table_name="item_links")
    op.drop_table("item_links")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_session_start"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_item_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_timestamp"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_item_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("user_config")
    op.drop_index(op.f("ix_token_usage_user_id"), table_name="token_usage")
    op.drop_index(op.f("ix_token_usage_timestamp"), table_name="token_usage")
    op.drop_table("token_usage")
    op.drop_index(op.f("ix_items_user_id"), table_name="items")
    op.drop_index(op.f("ix_items_state"), table_name="items")
    op.drop_index(op.f("ix_items_next_surface"), table_name="items")
    op.drop_index(op.f("ix_items_category"), table_name="items")
    op.drop_index("idx_items_tags", table_name="items", postgresql_using="gin")
    op.drop_index("idx_items_search_vector", table_name="items", postgresql_using="gin")
    op.drop_table("items")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("prompts")
    # ### end Alembic commands ###

    # Drop enum type
    op.execute("DROP TYPE IF EXISTS item_state;")
